### ISSUE TITLE
Question: Mapping of Cyclomatic Complexity metrics to the FBD

### ISSUE THREAD

**Issue by peda1337** [amuslija/fbd-complexity-tool#1]
Hey, in your readme you stated: 

Mapping of these complexity metrics (Number of Elements metric relates to the Lines of Code metric for general purpose programming languages) to the FBD syntax has been done and documented in a research paper (link).

Unfortunately, there is no link to the research paper. Can you help me sending me the paper? I need to know how you mapped the CC to predefined FBs like TON, TOF and so on.

Best, regards
Peter Gsellmann

**Comment by amuslija** [comment]
Hi Peter,

Cyclomatic Complexity for TON and TOF blocks has been calculated using the same technique as for any other conditional block (that is, each TON/TOF block would increase the overall CC by 1).

You can find the details and result of measurements on an industrial control system in the [paper](http://mdh.diva-portal.org/smash/record.jsf?pid=diva2%3A1113035&dswid=9058).

Sorry for the late response,
Adnan
