### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by MartinMelikMerkumians** [amuslija/fbd-complexity-tool#2]
Hi,

your tool is quite interesting, but you do not give details under what license you want to use?
Could you please add a license, so this is clear to potential users?

Best,
Martin

**Comment by amuslija** [comment]
Hi Martin,

Thanks for taking interest in the tool! I have added a standard MIT License. Let me know if you need anything else. 

Cheers,
Adnan

**Comment by MartinMelikMerkumians** [comment]
Thank you very much!
